name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev build-essential

      - name: Install buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython
          pip install "python-for-android>=2024.7.1"

      - name: Build debug APK
        env:
          BUILDOZER_WARN_ON_ROOT: "1"
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk